const JOBID =  Object.freeze(
	{
		JT_NOVICE : 0,
		JT_SWORDMAN : 1,
		JT_MAGICIAN : 2,
		JT_ARCHER : 3,
		JT_ACOLYTE : 4,
		JT_MERCHANT : 5,
		JT_THIEF : 6,
	
		JT_KNIGHT : 7,
		JT_PRIEST : 8,
		JT_WIZARD : 9,
		JT_BLACKSMITH : 10,
		JT_HUNTER : 11,
		JT_ASSASSIN : 12,
	
		JT_CRUSADER : 14,
		JT_MONK : 15,
		JT_SAGE : 16,
		JT_ROGUE : 17,
		JT_ALCHEMIST : 18,
		JT_BARD : 19,
		JT_DANCER : 20,
	
		JT_SUPERNOVICE : 23,
		JT_GUNSLINGER : 24,
		JT_NINJA : 25,
	
		JT_NOVICE_H : 4001,
	
		JT_SWORDMAN_H : 4002,			
		JT_MAGICIAN_H : 4003,			
		JT_ARCHER_H : 4004,			
		JT_ACOLYTE_H : 4005,
		JT_MERCHANT_H : 4006,			
		JT_THIEF_H : 4007,
	
		JT_KNIGHT_H : 4008,
		JT_PRIEST_H : 4009,
		JT_WIZARD_H : 4010,
		JT_BLACKSMITH_H : 4011,
		JT_HUNTER_H : 4012,
		JT_ASSASSIN_H : 4013,
	
		JT_CRUSADER_H : 4015,
		JT_MONK_H : 4016,
		JT_SAGE_H : 4017,
		JT_ROGUE_H : 4018,
		JT_ALCHEMIST_H : 4019,
		JT_BARD_H : 4020,
		JT_DANCER_H : 4021,
	
		JT_NOVICE_B : 4023,		
	
		JT_SWORDMAN_B : 4024,
		JT_MAGICIAN_B : 4025,			
		JT_ARCHER_B : 4026,			
		JT_ACOLYTE_B : 4027,
		JT_MERCHANT_B : 4028,
		JT_THIEF_B : 4029,		
	
		JT_KNIGHT_B : 4030,			
		JT_PRIEST_B : 4031,
		JT_WIZARD_B : 4032,
		JT_BLACKSMITH_B : 4033,
		JT_HUNTER_B : 4034,			
		JT_ASSASSIN_B : 4035,
	
		JT_CRUSADER_B : 4037,			
		JT_MONK_B : 4038,				
		JT_SAGE_B : 4039,				
		JT_ROGUE_B : 4040,
		JT_ALCHEMIST_B : 4041,
		JT_BARD_B : 4042,
		JT_DANCER_B : 4043,
	
		JT_SUPERNOVICE_B : 4045,
	
		JT_TAEKWON : 4046,
		JT_STAR : 4047,
		JT_STAR2 : 4048,
		JT_LINKER : 4049,
	
		JT_RUNE_KNIGHT : 4054,
		JT_WARLOCK : 4055,
		JT_RANGER : 4056,
		JT_ARCHBISHOP : 4057,
		JT_MECHANIC : 4058,
		JT_GUILLOTINE_CROSS : 4059,
	
		JT_RUNE_KNIGHT_H : 4060,
		JT_WARLOCK_H : 4061,
		JT_RANGER_H : 4062,
		JT_ARCHBISHOP_H : 4063,	
		JT_MECHANIC_H : 4064,
		JT_GUILLOTINE_CROSS_H : 4065,
	
		JT_ROYAL_GUARD : 4066,
		JT_SORCERER : 4067,
		JT_MINSTREL : 4068,
		JT_WANDERER : 4069,
		JT_SURA : 4070,
		JT_GENETIC : 4071,
		JT_SHADOW_CHASER : 4072,
	
		JT_ROYAL_GUARD_H : 4073,
		JT_SORCERER_H : 4074,
		JT_MINSTREL_H : 4075,
		JT_WANDERER_H : 4076,
		JT_SURA_H : 4077,
		JT_GENETIC_H : 4078,
		JT_SHADOW_CHASER_H : 4079,
		
		JT_RUNE_KNIGHT_B : 4096,
		JT_WARLOCK_B : 4097,
		JT_RANGER_B : 4098,
		JT_ARCHBISHOP_B : 4099,
		JT_MECHANIC_B : 4100,
		JT_GUILLOTINE_CROSS_B : 4101,
	
		JT_ROYAL_GUARD_B : 4102,
		JT_SORCERER_B : 4103,
		JT_MINSTREL_B : 4104,
		JT_WANDERER_B : 4105,
		JT_SURA_B : 4106,			
		JT_GENETIC_B : 4107,			
		JT_SHADOW_CHASER_B : 4108,
		JT_SUPERNOVICE2		:	4190,
		JT_KAGEROU : 4211, 
		JT_OBORO		: 4212,
		JT_REBELLION		: 4215,
	
		JT_DO_SUMMONER   : 4218,
	
		JT_DO_SUMMONER_B   : 4220,
	
		JT_NINJA_B   : 4222,
		JT_KAGEROU_B   : 4223,
		JT_OBORO_B   : 4224,
		JT_TAEKWON_B   : 4225,
		JT_STAR_B   : 4226,
		JT_LINKER_B   : 4227,
		JT_GUNSLINGER_B   : 4228,
		JT_REBELLION_B   : 4229,
	
		JT_STAR_EMPEROR   : 4239,
		JT_SOUL_REAPER   : 4240,
		JT_STAR_EMPEROR_B   : 4241,
		JT_SOUL_REAPER_B   : 4242,
	
		JT_DRAGON_KNIGHT	:	4252,
		JT_MEISTER			:	4253,
		JT_SHADOW_CROSS		:	4254,
		JT_ARCH_MAGE		:	4255,
		JT_CARDINAL			:	4256,
		JT_WINDHAWK			:	4257,
		JT_IMPERIAL_GUARD	:	4258,
		JT_BIOLO			:	4259,
		JT_ABYSS_CHASER		:	4260,
		JT_ELEMENTAL_MASTER	:	4261,
		JT_INQUISITOR		:	4262,
		JT_TROUBADOUR		:	4263,
		JT_TROUVERE			:	4264,
	
		JT_SKY_EMPEROR	: 4302,
		JT_SOUL_ASCETIC: 4303,
		JT_SHINKIRO	: 4304,
		JT_SHIRANUI	: 4305,
		JT_NIGHT_WATCH	: 4306,
		JT_HYPER_NOVICE	: 4307,
		JT_SPIRIT_HANDLER	: 4308,
	});
	
const PCJobNameTable =
{
	[JOBID.JT_NOVICE]				: "Novice",
	[JOBID.JT_NOVICE_H]				: "Novice High",

	// 1차
	[JOBID.JT_SWORDMAN]				: "Swordman",
	[JOBID.JT_MAGICIAN]				: "Magician",
	[JOBID.JT_MERCHANT]				: "Merchant",
	[JOBID.JT_ACOLYTE]				: "Acolyte",
	[JOBID.JT_THIEF]				: "Thief",
	[JOBID.JT_ARCHER]				: "Archer",
	
	// 전승 1차
	[JOBID.JT_SWORDMAN_H]			: "Swordman High",
	[JOBID.JT_MAGICIAN_H]			: "Magician High",
	[JOBID.JT_MERCHANT_H]			: "Merchant High",
	[JOBID.JT_ACOLYTE_H]			: "Acolyte High",
	[JOBID.JT_THIEF_H]				: "Thief High",
	[JOBID.JT_ARCHER_H]				: "Archer High",

	// 2-1차
	[JOBID.JT_KNIGHT]				: "Knight",
	[JOBID.JT_WIZARD]				: "Wizard",
	[JOBID.JT_BLACKSMITH]			: "Blacksmith",
	[JOBID.JT_PRIEST]				: "Priest",
	[JOBID.JT_ASSASSIN]				: "Assassin",
	[JOBID.JT_HUNTER]				: "Hunter",

	// 전승 2-1차
	[JOBID.JT_KNIGHT_H]				: "Lord Knight",
	[JOBID.JT_WIZARD_H]				: "High Wizard",
	[JOBID.JT_BLACKSMITH_H]			: "White Smith",
	[JOBID.JT_PRIEST_H]				: "High Priest",
	[JOBID.JT_ASSASSIN_H]			: "Assassin Cross",
	[JOBID.JT_HUNTER_H]				: "Sniper",

	// 3-1차
	[JOBID.JT_RUNE_KNIGHT]			: "Rune Knight",
	[JOBID.JT_WARLOCK]				: "Warlock",
	[JOBID.JT_MECHANIC]				: "Mechanic",
	[JOBID.JT_ARCHBISHOP]			: "Arch Bishop",
	[JOBID.JT_GUILLOTINE_CROSS]		: "Glt. Cross",
	[JOBID.JT_RANGER]				: "Ranger",

	// 전승 3-1차
	[JOBID.JT_RUNE_KNIGHT_H]		: "Rune Knight",
	[JOBID.JT_WARLOCK_H]			: "Warlock",
	[JOBID.JT_MECHANIC_H]			: "Mechanic",
	[JOBID.JT_ARCHBISHOP_H]			: "Arch Bishop",
	[JOBID.JT_GUILLOTINE_CROSS_H]	: "Glt. Cross",
	[JOBID.JT_RANGER_H]				: "Ranger",

	// 4-1차
	[JOBID.JT_DRAGON_KNIGHT]		: "Dragon Knight",
	[JOBID.JT_ARCH_MAGE]			: "Arch Mage",
	[JOBID.JT_MEISTER]				: "Meister",
	[JOBID.JT_CARDINAL]				: "Cardinal",
	[JOBID.JT_SHADOW_CROSS]			: "Shadow Cross",
	[JOBID.JT_WINDHAWK]				: "Windhawk",

	// 2-2차
	[JOBID.JT_CRUSADER]				: "Crusader",
	[JOBID.JT_SAGE]					: "Sage",
	[JOBID.JT_ALCHEMIST]			: "Alchemist",
	[JOBID.JT_MONK]					: "Monk",
	[JOBID.JT_ROGUE]				: "Rogue",
	[JOBID.JT_BARD]					: "Bard",
	[JOBID.JT_DANCER]				: "Dancer",

	// 전승 2-2차
	[JOBID.JT_CRUSADER_H]			: "Paladin",
	[JOBID.JT_SAGE_H]				: "Professor",
	[JOBID.JT_ALCHEMIST_H]			: "Creator",
	[JOBID.JT_MONK_H]				: "Champion",
	[JOBID.JT_ROGUE_H]				: "Stalker",
	[JOBID.JT_BARD_H]				: "Clown",
	[JOBID.JT_DANCER_H]				: "Gypsy",

	// 3-2차
	[JOBID.JT_ROYAL_GUARD]			: "Royal Guard",
	[JOBID.JT_SORCERER]				: "Sorcerer",
	[JOBID.JT_GENETIC]				: "Genetic",
	[JOBID.JT_SURA]					: "Sura",
	[JOBID.JT_SHADOW_CHASER]		: "Shadow Chaser",
	[JOBID.JT_MINSTREL]				: "Minstrel",
	[JOBID.JT_WANDERER]				: "Wanderer",

	// 전승 3-2차
	[JOBID.JT_ROYAL_GUARD_H]		: "Royal Guard",
	[JOBID.JT_SORCERER_H]			: "Sorcerer",
	[JOBID.JT_GENETIC_H]			: "Genetic",
	[JOBID.JT_SURA_H]				: "Sura",
	[JOBID.JT_SHADOW_CHASER_H]		: "Shadow Chaser",
	[JOBID.JT_MINSTREL_H]			: "Minstrel",
	[JOBID.JT_WANDERER_H]			: "Wanderer",

	// 4-2차
	[JOBID.JT_IMPERIAL_GUARD]		: "Imperial Guard",
	[JOBID.JT_ELEMENTAL_MASTER]		: "Elemental Master",
	[JOBID.JT_BIOLO]				: "Biolo",
	[JOBID.JT_INQUISITOR]			: "Inquisitor",
	[JOBID.JT_ABYSS_CHASER]			: "Abyss Chaser",
	[JOBID.JT_TROUBADOUR]			: "Troubadour",
	[JOBID.JT_TROUVERE]				: "Trouvere",

	// 확장 1차
	[JOBID.JT_TAEKWON]				: "태권",
	[JOBID.JT_NINJA]				: "Ninja",
	[JOBID.JT_GUNSLINGER]			: "Gunslinger",
	[JOBID.JT_SUPERNOVICE]			: "Super Novice",
	[JOBID.JT_DO_SUMMONER]			: "Summoner",

	// 확장 2차
	[JOBID.JT_STAR]					: "권성",
	[JOBID.JT_STAR2]				: "권성",	// 융합
	[JOBID.JT_LINKER]				: "소울링커",

	// 상위 확장
	[JOBID.JT_STAR_EMPEROR]			: "성제",
	[JOBID.JT_STAR2_EMPEROR]		: "성제",	// 융합
	[JOBID.JT_SOUL_REAPER]			: "소울리퍼",
	[JOBID.JT_KAGEROU]				: "Kagerou",
	[JOBID.JT_OBORO]				: "Oboro",
	[JOBID.JT_REBELLION]			: "Rebellion",
	[JOBID.JT_SUPERNOVICE2]			: "Super Novice",

	// 2차 상위 확장
	[JOBID.JT_SKY_EMPEROR]			: "천제",
	[JOBID.JT_SKY_EMPEROR2]			: "천제",	// 융합
	[JOBID.JT_SOUL_ASCETIC]			: "영도사",
	[JOBID.JT_SHINKIRO]				: "Shinkiro",
	[JOBID.JT_SHIRANUI]				: "Shiranui",
	[JOBID.JT_NIGHT_WATCH]			: "Night Watch",
	[JOBID.JT_HYPER_NOVICE]			: "Hyper Novice",
	[JOBID.JT_SPIRIT_HANDLER]		: "Spirit Handler",

	// Baby ////////////////////////////////////////////////////-
	[JOBID.JT_NOVICE_B]				: "Baby",

	// 1차
	[JOBID.JT_SWORDMAN_B]			: "Baby Swordman",
	[JOBID.JT_MAGICIAN_B]			: "Baby Magician",
	[JOBID.JT_MERCHANT_B]			: "Baby Merchant",
	[JOBID.JT_ACOLYTE_B]			: "Baby Acolyte",
	[JOBID.JT_THIEF_B]				: "Baby Thief",
	[JOBID.JT_ARCHER_B]				: "Baby Archer",

	// 2-1차
	[JOBID.JT_KNIGHT_B]				: "Baby Knight",
	[JOBID.JT_WIZARD_B]				: "Baby Wizard",
	[JOBID.JT_BLACKSMITH_B]			: "Baby Blacksmith",
	[JOBID.JT_PRIEST_B]				: "Baby Priest",
	[JOBID.JT_ASSASSIN_B]			: "Baby Assassin",
	[JOBID.JT_HUNTER_B]				: "Baby Hunter",


	// 2-2차
	[JOBID.JT_CRUSADER_B]			: "Baby Crusader",
	[JOBID.JT_SAGE_B]				: "Baby Sage",
	[JOBID.JT_ALCHEMIST_B]			: "Baby Alchemist",
	[JOBID.JT_MONK_B]				: "Baby Monk",
	[JOBID.JT_ROGUE_B]				: "Baby Rogue",
	[JOBID.JT_BARD_B]				: "Baby Bard",
	[JOBID.JT_DANCER_B]				: "Baby Dancer",


	// 3-1차
	[JOBID.JT_RUNE_KNIGHT_B]		: "Baby Rune",
	[JOBID.JT_WARLOCK_B]			: "Baby Warlock",
	[JOBID.JT_MECHANIC_B]			: "Baby Mechanic",
	[JOBID.JT_ARCHBISHOP_B]			: "Baby Bishop",
	[JOBID.JT_GUILLOTINE_CROSS_B]	: "Baby Cross",
	[JOBID.JT_RANGER_B]				: "Baby Ranger",
	
	// 3-2차
	[JOBID.JT_ROYAL_GUARD_B]		: "Baby Guard",
	[JOBID.JT_SORCERER_B]			: "Baby Sorcerer",
	[JOBID.JT_GENETIC_B]			: "Baby Genetic",
	[JOBID.JT_SURA_B]				: "Baby Sura",
	[JOBID.JT_SHADOW_CHASER_B]		: "Baby Chaser",
	[JOBID.JT_MINSTREL_B]			: "Baby Minstrel",
	[JOBID.JT_WANDERER_B]			: "Baby Wanderer",
	
	// 확장 1차
	[JOBID.JT_TAEKWON_B]			: "Baby TaeKwon",
	[JOBID.JT_NINJA_B]				: "Baby Ninja",
	[JOBID.JT_GUNSLINGER_B]			: "Baby Gunslinger",
	[JOBID.JT_SUPERNOVICE_B]		: "Super Baby",
	[JOBID.JT_DO_SUMMONER_B]		: "Baby Summoner",

	// 확장 2차
	[JOBID.JT_STAR_B]				: "Baby Star Gladiator",
	[JOBID.JT_STAR2_B]				: "Baby Star Gladiator",	// 융합
	[JOBID.JT_LINKER_B]				: "Baby Soul Linker",

	// 상위 확장
	[JOBID.JT_STAR_EMPEROR_B]		: "Baby Star Emperor",
	[JOBID.JT_STAR2_EMPEROR_B]		: "Baby Star Emperor",		// 융합
	[JOBID.JT_SOUL_REAPER_B]		: "Baby Soul Reaper",
	[JOBID.JT_KAGEROU_B]			: "Baby Kagerou",
	[JOBID.JT_OBORO_B]				: "Baby Oboro",
	[JOBID.JT_REBELLION_B]			: "Baby Rebellion",
	[JOBID.JT_SUPERNOVICE2_B]		: "Baby Super Novice",

	// 세컨드 코스츔
	[JOBID.JT_RUNE_KNIGHT_2ND]		: "Rune Knight 2ND",
	[JOBID.JT_MECHANIC_2ND]		: "Mechanic 2ND",
	[JOBID.JT_GUILLOTINE_CROSS_2ND]		: "Guillotine Cross 2ND",
	[JOBID.JT_WARLOCK_2ND]		: "Warlock 2ND",
	[JOBID.JT_ARCHBISHOP_2ND]		: "Archbishop 2ND",
	[JOBID.JT_RANGER_2ND]		: "Ranger 2ND",
	[JOBID.JT_ROYAL_GUARD_2ND]		: "Royal Guard 2ND",
	[JOBID.JT_GENETIC_2ND]		: "Genetic 2ND",
	[JOBID.JT_SHADOW_CHASER_2ND]		: "Shadow Chaser 2ND",
	[JOBID.JT_SORCERER_2ND]		: "Sorcerer 2ND",
	[JOBID.JT_SURA_2ND]		: "Sura 2ND",
	[JOBID.JT_MINSTREL_2ND]		: "Minstrel 2ND",
	[JOBID.JT_WANDERER_2ND]		: "Wanderer 2ND",
}
	
const JOBGROUP_NV = [
	JOBID.JT_SWORDMAN, 
	JOBID.JT_MAGICIAN, 
	JOBID.JT_ARCHER, 
	JOBID.JT_ACOLYTE, 
	JOBID.JT_MERCHANT, 
	JOBID.JT_THIEF,
	JOBID.JT_TAEKWON,
	JOBID.JT_NINJA,
	JOBID.JT_GUNSLINGER,
	JOBID.JT_SUPERNOVICE
];
const JOBGROUP_H = [
	JOBID.JT_KNIGHT_H,
	JOBID.JT_PRIEST_H,
	JOBID.JT_WIZARD_H,
	JOBID.JT_BLACKSMITH_H,
	JOBID.JT_HUNTER_H,
	JOBID.JT_ASSASSIN_H,

	JOBID.JT_CRUSADER_H,
	JOBID.JT_MONK_H,
	JOBID.JT_SAGE_H,
	JOBID.JT_ROGUE_H,
	JOBID.JT_ALCHEMIST_H,
	JOBID.JT_BARD_H,
	JOBID.JT_DANCER_H,
];	

const JOB_BASE_MAP = {
    [JOBID.JT_KNIGHT_H]: JOBID.JT_KNIGHT,
    [JOBID.JT_PRIEST_H]: JOBID.JT_PRIEST,
    [JOBID.JT_WIZARD_H]: JOBID.JT_WIZARD,
    [JOBID.JT_BLACKSMITH_H]: JOBID.JT_BLACKSMITH,
    [JOBID.JT_HUNTER_H]: JOBID.JT_HUNTER,
    [JOBID.JT_ASSASSIN_H]: JOBID.JT_ASSASSIN,
    [JOBID.JT_CRUSADER_H]: JOBID.JT_CRUSADER,
    [JOBID.JT_MONK_H]: JOBID.JT_MONK,
    [JOBID.JT_SAGE_H]: JOBID.JT_SAGE,
    [JOBID.JT_ROGUE_H]: JOBID.JT_ROGUE,
    [JOBID.JT_ALCHEMIST_H]: JOBID.JT_ALCHEMIST,
    [JOBID.JT_BARD_H]: JOBID.JT_BARD,
    [JOBID.JT_DANCER_H]: JOBID.JT_DANCER,
};

const JOB_INHERIT_LIST =
{
	[JOBID.JT_SWORDMAN] : JOBID.JT_NOVICE,
	[JOBID.JT_MAGICIAN] : JOBID.JT_NOVICE,
	[JOBID.JT_ARCHER] : JOBID.JT_NOVICE,
	[JOBID.JT_ACOLYTE] : JOBID.JT_NOVICE,
	[JOBID.JT_MERCHANT] : JOBID.JT_NOVICE,
	[JOBID.JT_THIEF] : JOBID.JT_NOVICE,

	[JOBID.JT_KNIGHT] : JOBID.JT_SWORDMAN,
	[JOBID.JT_PRIEST] : JOBID.JT_ACOLYTE,
	[JOBID.JT_WIZARD] : JOBID.JT_MAGICIAN,
	[JOBID.JT_BLACKSMITH] : JOBID.JT_MERCHANT,
	[JOBID.JT_HUNTER] : JOBID.JT_ARCHER,
	[JOBID.JT_ASSASSIN] : JOBID.JT_THIEF,

	[JOBID.JT_CRUSADER] : JOBID.JT_SWORDMAN,
	[JOBID.JT_MONK] : JOBID.JT_ACOLYTE,
	[JOBID.JT_SAGE] : JOBID.JT_MAGICIAN,
	[JOBID.JT_ROGUE] : JOBID.JT_THIEF,
	[JOBID.JT_ALCHEMIST] : JOBID.JT_MERCHANT,
	[JOBID.JT_BARD] : JOBID.JT_ARCHER,
	[JOBID.JT_DANCER] : JOBID.JT_ARCHER,

	[JOBID.JT_SUPERNOVICE] : JOBID.JT_NOVICE,

	[JOBID.JT_GUNSLINGER] : JOBID.JT_NOVICE,
	[JOBID.JT_NINJA] : JOBID.JT_NOVICE,

	[JOBID.JT_NOVICE_H] : JOBID.JT_NOVICE,
	[JOBID.JT_SWORDMAN_H] : JOBID.JT_SWORDMAN,
	[JOBID.JT_MAGICIAN_H] : JOBID.JT_MAGICIAN,
	[JOBID.JT_ARCHER_H] : JOBID.JT_ARCHER,
	[JOBID.JT_ACOLYTE_H] : JOBID.JT_ACOLYTE,
	[JOBID.JT_MERCHANT_H] : JOBID.JT_MERCHANT,
	[JOBID.JT_THIEF_H] : JOBID.JT_THIEF,

	[JOBID.JT_KNIGHT_H] : JOBID.JT_KNIGHT,
	[JOBID.JT_PRIEST_H] : JOBID.JT_PRIEST,
	[JOBID.JT_WIZARD_H] : JOBID.JT_WIZARD,
	[JOBID.JT_BLACKSMITH_H] : JOBID.JT_BLACKSMITH,
	[JOBID.JT_HUNTER_H] : JOBID.JT_HUNTER,
	[JOBID.JT_ASSASSIN_H] : JOBID.JT_ASSASSIN,
	
	[JOBID.JT_CRUSADER_H] : JOBID.JT_CRUSADER,
	[JOBID.JT_MONK_H] : JOBID.JT_MONK,
	[JOBID.JT_SAGE_H] : JOBID.JT_SAGE,
	[JOBID.JT_ROGUE_H] : JOBID.JT_ROGUE,
	[JOBID.JT_ALCHEMIST_H] : JOBID.JT_ALCHEMIST,
	[JOBID.JT_BARD_H] : JOBID.JT_BARD,
	[JOBID.JT_DANCER_H] : JOBID.JT_DANCER,

	[JOBID.JT_NOVICE_B] : JOBID.JT_NOVICE,
	[JOBID.JT_SWORDMAN_B] : JOBID.JT_SWORDMAN,
	[JOBID.JT_MAGICIAN_B] : JOBID.JT_MAGICIAN,
	[JOBID.JT_ARCHER_B] : JOBID.JT_ARCHER,
	[JOBID.JT_ACOLYTE_B] : JOBID.JT_ACOLYTE,
	[JOBID.JT_MERCHANT_B] : JOBID.JT_MERCHANT,
	[JOBID.JT_THIEF_B] : JOBID.JT_THIEF,

	[JOBID.JT_KNIGHT_B] : JOBID.JT_KNIGHT,
	[JOBID.JT_PRIEST_B] : JOBID.JT_PRIEST,
	[JOBID.JT_WIZARD_B] : JOBID.JT_WIZARD,
	[JOBID.JT_BLACKSMITH_B] : JOBID.JT_BLACKSMITH,
	[JOBID.JT_HUNTER_B] : JOBID.JT_HUNTER,
	[JOBID.JT_ASSASSIN_B] : JOBID.JT_ASSASSIN,

	[JOBID.JT_CRUSADER_B] : JOBID.JT_CRUSADER,
	[JOBID.JT_MONK_B] : JOBID.JT_MONK,
	[JOBID.JT_SAGE_B] : JOBID.JT_SAGE,
	[JOBID.JT_ROGUE_B] : JOBID.JT_ROGUE,
	[JOBID.JT_ALCHEMIST_B] : JOBID.JT_ALCHEMIST,
	[JOBID.JT_BARD_B] : JOBID.JT_BARD,
	[JOBID.JT_DANCER_B] : JOBID.JT_DANCER,

	[JOBID.JT_SUPERNOVICE_B] : JOBID.JT_SUPERNOVICE,
	
	[JOBID.JT_TAEKWON] : JOBID.JT_NOVICE,
	[JOBID.JT_STAR] : JOBID.JT_TAEKWON,
	[JOBID.JT_LINKER] : JOBID.JT_TAEKWON,

	[JOBID.JT_RUNE_KNIGHT] : JOBID.JT_KNIGHT,
	[JOBID.JT_WARLOCK] : JOBID.JT_WIZARD,
	[JOBID.JT_RANGER] : JOBID.JT_HUNTER,
	[JOBID.JT_ARCHBISHOP] : JOBID.JT_PRIEST,
	[JOBID.JT_MECHANIC] : JOBID.JT_BLACKSMITH,
	[JOBID.JT_GUILLOTINE_CROSS] : JOBID.JT_ASSASSIN,

	[JOBID.JT_RUNE_KNIGHT_H] : JOBID.JT_KNIGHT_H,
	[JOBID.JT_WARLOCK_H] : JOBID.JT_WIZARD_H,
	[JOBID.JT_RANGER_H] : JOBID.JT_HUNTER_H,
	[JOBID.JT_ARCHBISHOP_H] : JOBID.JT_PRIEST_H,
	[JOBID.JT_MECHANIC_H] : JOBID.JT_BLACKSMITH_H,
	[JOBID.JT_GUILLOTINE_CROSS_H] : JOBID.JT_ASSASSIN_H,

	[JOBID.JT_ROYAL_GUARD] : JOBID.JT_CRUSADER, 
	[JOBID.JT_SORCERER] : JOBID.JT_SAGE,
	[JOBID.JT_MINSTREL] : JOBID.JT_BARD,
	[JOBID.JT_WANDERER] : JOBID.JT_DANCER,
	[JOBID.JT_SURA] : JOBID.JT_MONK,
	[JOBID.JT_GENETIC] : JOBID.JT_ALCHEMIST,
	[JOBID.JT_SHADOW_CHASER] : JOBID.JT_ROGUE,

	[JOBID.JT_ROYAL_GUARD_H] : JOBID.JT_CRUSADER_H,
	[JOBID.JT_SORCERER_H] : JOBID.JT_SAGE_H,
	[JOBID.JT_MINSTREL_H] : JOBID.JT_BARD_H,
	[JOBID.JT_WANDERER_H] : JOBID.JT_DANCER_H,
	[JOBID.JT_SURA_H] : JOBID.JT_MONK_H,
	[JOBID.JT_GENETIC_H] : JOBID.JT_ALCHEMIST_H,
	[JOBID.JT_SHADOW_CHASER_H] : JOBID.JT_ROGUE_H,

	[JOBID.JT_RUNE_KNIGHT_B] : JOBID.JT_RUNE_KNIGHT,
	[JOBID.JT_WARLOCK_B] : JOBID.JT_WARLOCK,
	[JOBID.JT_RANGER_B] : JOBID.JT_RANGER,
	[JOBID.JT_ARCHBISHOP_B] : JOBID.JT_ARCHBISHOP,
	[JOBID.JT_MECHANIC_B] : JOBID.JT_MECHANIC,
	[JOBID.JT_GUILLOTINE_CROSS_B] : JOBID.JT_GUILLOTINE_CROSS,

	[JOBID.JT_ROYAL_GUARD_B] : JOBID.JT_ROYAL_GUARD,
	[JOBID.JT_SORCERER_B] : JOBID.JT_SORCERER,
	[JOBID.JT_MINSTREL_B] : JOBID.JT_MINSTREL,
	[JOBID.JT_WANDERER_B] : JOBID.JT_WANDERER,
	[JOBID.JT_SURA_B] : JOBID.JT_SURA,
	[JOBID.JT_GENETIC_B] : JOBID.JT_GENETIC,
	[JOBID.JT_SHADOW_CHASER_B] : JOBID.JT_SHADOW_CHASER,
	
	[JOBID.JT_SUPERNOVICE2] : JOBID.JT_SUPERNOVICE,

	[JOBID.JT_SUPERNOVICE2_B] : JOBID.JT_SUPERNOVICE2,
	[JOBID.JT_TAEKWON_B] : JOBID.JT_TAEKWON ,
	[JOBID.JT_NINJA_B] : JOBID.JT_NINJA,
	[JOBID.JT_GUNSLINGER_B] : JOBID.JT_GUNSLINGER,
	[JOBID.JT_LINKER_B] : JOBID.JT_LINKER,
	[JOBID.JT_STAR_B] : JOBID.JT_STAR,

	[JOBID.JT_KAGEROU] : JOBID.JT_NINJA,
	[JOBID.JT_OBORO] : JOBID.JT_NINJA,
	[JOBID.JT_REBELLION] : JOBID.JT_GUNSLINGER,

	[JOBID.JT_KAGEROU_B] : JOBID.JT_KAGEROU,
	[JOBID.JT_OBORO_B] : JOBID.JT_OBORO,
	[JOBID.JT_REBELLION_B] : JOBID.JT_REBELLION,

	[JOBID.JT_STAR_EMPEROR] : JOBID.JT_STAR,
	[JOBID.JT_SOUL_REAPER] : JOBID.JT_LINKER,
	
	[JOBID.JT_STAR_EMPEROR_B] : JOBID.JT_STAR_EMPEROR,
	[JOBID.JT_SOUL_REAPER_B] : JOBID.JT_SOUL_REAPER,
	[JOBID.JT_DO_SUMMONER_B] : JOBID.JT_DO_SUMMONER,

	[JOBID.JT_DRAGON_KNIGHT] : JOBID.JT_RUNE_KNIGHT_H,
	[JOBID.JT_SHADOW_CROSS] : JOBID.JT_GUILLOTINE_CROSS_H,
	[JOBID.JT_ARCH_MAGE] : JOBID.JT_WARLOCK_H,
	[JOBID.JT_CARDINAL] : JOBID.JT_ARCHBISHOP_H,
	[JOBID.JT_WINDHAWK] : JOBID.JT_RANGER_H,	
	[JOBID.JT_IMPERIAL_GUARD] : JOBID.JT_ROYAL_GUARD_H,
	[JOBID.JT_BIOLO] : JOBID.JT_GENETIC_H,
	[JOBID.JT_ABYSS_CHASER] : JOBID.JT_SHADOW_CHASER_H,
	[JOBID.JT_ELEMENTAL_MASTER] : JOBID.JT_SORCERER_H,
	[JOBID.JT_INQUISITOR] : JOBID.JT_SURA_H,
	[JOBID.JT_MEISTER] : JOBID.JT_MECHANIC_H,
	[JOBID.JT_TROUBADOUR] : JOBID.JT_MINSTREL_H,
	[JOBID.JT_TROUVERE] : JOBID.JT_WANDERER_H,

	[JOBID.JT_SKY_EMPEROR] : JOBID.JT_STAR_EMPEROR,
	[JOBID.JT_SOUL_ASCETIC] : JOBID.JT_SOUL_REAPER,
	[JOBID.JT_NIGHT_WATCH] : JOBID.JT_REBELLION,
	[JOBID.JT_SHIRANUI] : JOBID.JT_OBORO,
	[JOBID.JT_SHINKIRO] : JOBID.JT_KAGEROU,
	[JOBID.JT_HYPER_NOVICE] : JOBID.JT_SUPERNOVICE2,
	[JOBID.JT_SPIRIT_HANDLER] : JOBID.JT_DO_SUMMONER,
}

const BASE_MAX1 = 99;
const BASE_MAX2 = 200;
const BASE_MAX3 = 275;
const JOB_MAX1 = 50;
const JOB_MAX2 = 60;
const JOB_MAX3 = 70;
const JOB_MAX4 = 60;
const JOB_MAXNV = 99;

const JOB_SETTING = 
	{
		[JOBID.JT_NOVICE] : [BASE_MAX1, 10],
		[JOBID.JT_SWORDMAN] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_MAGICIAN] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_ARCHER] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_ACOLYTE] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_MERCHANT] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_THIEF] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_KNIGHT] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_PRIEST] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_WIZARD] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_BLACKSMITH] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_HUNTER] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_ASSASSIN] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_CRUSADER] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_MONK] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_SAGE] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_ROGUE] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_ALCHEMIST] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_BARD] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_DANCER] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_SUPERNOVICE] : [BASE_MAX1, JOB_MAXNV],
		[JOBID.JT_GUNSLINGER] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_NINJA] : [BASE_MAX1, JOB_MAX3],
	
		[JOBID.JT_NOVICE_H] : [BASE_MAX1, 10],
	
		[JOBID.JT_SWORDMAN_H] : [BASE_MAX1, JOB_MAX1],		
		[JOBID.JT_MAGICIAN_H] : [BASE_MAX1, JOB_MAX1],		
		[JOBID.JT_ARCHER_H] : [BASE_MAX1, JOB_MAX1],		
		[JOBID.JT_ACOLYTE_H] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_MERCHANT_H] : [BASE_MAX1, JOB_MAX1],		
		[JOBID.JT_THIEF_H] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_KNIGHT_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_PRIEST_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_WIZARD_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_BLACKSMITH_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_HUNTER_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_ASSASSIN_H] : [BASE_MAX1, JOB_MAX3],
	
		[JOBID.JT_CRUSADER_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_MONK_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_SAGE_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_ROGUE_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_ALCHEMIST_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_BARD_H] : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_DANCER_H] : [BASE_MAX1, JOB_MAX3],
	
		[JOBID.JT_NOVICE_B] : [BASE_MAX1, 9],	
	
		[JOBID.JT_SWORDMAN_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_MAGICIAN_B] : [BASE_MAX1, JOB_MAX1],		
		[JOBID.JT_ARCHER_B] : [BASE_MAX1, JOB_MAX1],	
		[JOBID.JT_ACOLYTE_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_MERCHANT_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_THIEF_B] : [BASE_MAX1, JOB_MAX1],	
	
		[JOBID.JT_KNIGHT_B] : [BASE_MAX1, JOB_MAX1],	
		[JOBID.JT_PRIEST_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_WIZARD_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_BLACKSMITH_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_HUNTER_B] : [BASE_MAX1, JOB_MAX1],	
		[JOBID.JT_ASSASSIN_B] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_CRUSADER_B] : [BASE_MAX1, JOB_MAX1],	
		[JOBID.JT_MONK_B] : [BASE_MAX1, JOB_MAX1],				
		[JOBID.JT_SAGE_B] : [BASE_MAX1, JOB_MAX1],			
		[JOBID.JT_ROGUE_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_ALCHEMIST_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_BARD_B] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_DANCER_B] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_SUPERNOVICE_B] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_TAEKWON] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_STAR] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_STAR2] : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_LINKER] : [BASE_MAX1, JOB_MAX1],
	
		[JOBID.JT_RUNE_KNIGHT] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_WARLOCK] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_RANGER] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_ARCHBISHOP] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_MECHANIC] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_GUILLOTINE_CROSS] : [BASE_MAX2, JOB_MAX3],
	
		[JOBID.JT_RUNE_KNIGHT_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_WARLOCK_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_RANGER_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_ARCHBISHOP_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_MECHANIC_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_GUILLOTINE_CROSS_H] : [BASE_MAX2, JOB_MAX3],
	
		[JOBID.JT_ROYAL_GUARD] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SORCERER] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_MINSTREL] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_WANDERER] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SURA] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_GENETIC] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SHADOW_CHASER] : [BASE_MAX2, JOB_MAX3],
	
		[JOBID.JT_ROYAL_GUARD_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SORCERER_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_MINSTREL_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_WANDERER_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SURA_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_GENETIC_H] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SHADOW_CHASER_H] : [BASE_MAX2, JOB_MAX3],
		
		[JOBID.JT_RUNE_KNIGHT_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_WARLOCK_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_RANGER_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_ARCHBISHOP_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_MECHANIC_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_GUILLOTINE_CROSS_B] : [BASE_MAX2, JOB_MAX3],
	
		[JOBID.JT_ROYAL_GUARD_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SORCERER_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_MINSTREL_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_WANDERER_B] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SURA_B] : [BASE_MAX2, JOB_MAX3],		
		[JOBID.JT_GENETIC_B] : [BASE_MAX2, JOB_MAX3],			
		[JOBID.JT_SHADOW_CHASER_B] : [BASE_MAX2, JOB_MAX3],

		[JOBID.JT_SUPERNOVICE2]		:	[BASE_MAX2, JOB_MAX3],
		[JOBID.JT_KAGEROU] : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_OBORO]		: [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_REBELLION]		: [BASE_MAX2, JOB_MAX3],
	
		[JOBID.JT_DO_SUMMONER]   : [BASE_MAX2, JOB_MAX2],
	
		[JOBID.JT_DO_SUMMONER_B]   : [BASE_MAX2, JOB_MAX2],
	
		[JOBID.JT_NINJA_B]   : [BASE_MAX1, JOB_MAX3],
		[JOBID.JT_KAGEROU_B]   : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_OBORO_B]   : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_TAEKWON_B]   : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_STAR_B]   : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_LINKER_B]   : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_GUNSLINGER_B]   : [BASE_MAX1, JOB_MAX1],
		[JOBID.JT_REBELLION_B]   : [BASE_MAX2, JOB_MAX3],
	
		[JOBID.JT_STAR_EMPEROR]   : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SOUL_REAPER]   : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_STAR_EMPEROR_B]   : [BASE_MAX2, JOB_MAX3],
		[JOBID.JT_SOUL_REAPER_B]   : [BASE_MAX2, JOB_MAX3],
	
		[JOBID.JT_DRAGON_KNIGHT]:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_MEISTER]			:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_SHADOW_CROSS]		:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_ARCH_MAGE]		:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_CARDINAL]			:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_WINDHAWK]			:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_IMPERIAL_GUARD]	:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_BIOLO]			:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_ABYSS_CHASER]		:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_ELEMENTAL_MASTER]	:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_INQUISITOR]		:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_TROUBADOUR]		:	[BASE_MAX3, JOB_MAX4],
		[JOBID.JT_TROUVERE]			:	[BASE_MAX3, JOB_MAX4],
	
		[JOBID.JT_SKY_EMPEROR]	: [BASE_MAX3, JOB_MAX4],
		[JOBID.JT_SOUL_ASCETIC]: [BASE_MAX3, JOB_MAX4],
		[JOBID.JT_SHINKIRO]	: [BASE_MAX3, JOB_MAX4],
		[JOBID.JT_SHIRANUI]	: [BASE_MAX3, JOB_MAX4],
		[JOBID.JT_NIGHT_WATCH]	: [BASE_MAX3, JOB_MAX4],
		[JOBID.JT_HYPER_NOVICE]	: [BASE_MAX3, JOB_MAX4],
		[JOBID.JT_SPIRIT_HANDLER]	: [BASE_MAX3, JOB_MAX4],
	}